basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: echenwen@gmail.com
    name: n3xtchen
    url: http://n3xtchen.github.io/n3xtchen
  description: This is a server for Gin 3at API.
  termsOfService: http://swagger.io/terms/
  title: Gin 3at
  version: "1.0"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
