flowchart TD
  %% 外部
  Client[应用终端]
  APIGW[API网关]

  %% 系统主框
  subgraph 系统
    direction TB
    subgraph 用户接口层
      Controller[控制器]
    end

    subgraph 应用层
    	direction LR
      subgraph AppService[应用服务层]
      	App[应用服务]
      end
      %% AppRepoPort[仓储接口]
      subgraph SharedService[共享服务层]
      	SessionRepoPort[通用服务仓储接口]
      end
      %% App --> SessionRepoPort
    end

    subgraph 领域层
      DomainService[领域服务]

      subgraph AggregatesA[聚合A]
        ValueObjA[实体/值对象A]
      end
      subgraph AggregatesB[聚合B]
        ValueObjB[实体/值对象B]
      end
      DomainRepoPort[仓储接口]
    end

    subgraph 基础层
    	subgraph 仓储实现
      	DAO[DAO]
      	SessionImp[通用服务实现]
      end
    	subgraph 数据库
      	PO[Model]
      	DB[(DB)]
      end
      
      subgraph 缓存
      	Redis[Redis]
      end
     
      subgraph 会话
      	File[文件]
      end
    end
  end

  %% 关系
  Client --> APIGW
  APIGW --> Controller
  Controller --> AppService
	%%Controller --> SharedService
  App --> DomainService
  App --> DomainRepoPort
	%%AppService --> SharedService
	
  DomainService --> AggregatesA
  DomainService --> AggregatesB
  AggregatesA --> ValueObjA
  AggregatesB --> ValueObjB
  AggregatesA --> DomainRepoPort
  AggregatesB --> DomainRepoPort

  DomainRepoPort --> DAO
  SessionRepoPort --> SessionImp
  DAO --> PO
  PO --> DB
  DAO --> Redis
  SessionImp --> File
 
