// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "n3xtchen",
            "url": "http://n3xtchen.github.io/n3xtchen",
            "email": "echenwen@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/orders": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Create a new order",
                "parameters": [
                    {
                        "description": "Order details",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrderReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Order created successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Inyernal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/dto.Code"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.Code": {
            "type": "integer",
            "enum": [
                0
            ],
            "x-enum-varnames": [
                "CodeSuccess"
            ]
        },
        "dto.CreateAddressReq": {
            "type": "object",
            "required": [
                "address",
                "name",
                "phone"
            ],
            "properties": {
                "address": {
                    "description": "Full address",
                    "type": "string",
                    "maxLength": 50
                },
                "name": {
                    "description": "Name of the person",
                    "type": "string",
                    "maxLength": 20
                },
                "phone": {
                    "description": "Phone number",
                    "type": "string"
                }
            }
        },
        "dto.CreateOrderItemReq": {
            "type": "object",
            "required": [
                "price",
                "product_id",
                "quantity"
            ],
            "properties": {
                "price": {
                    "description": "Price of the product at the time of order",
                    "type": "number"
                },
                "product_id": {
                    "description": "ID of the Product",
                    "type": "integer"
                },
                "quantity": {
                    "description": "Quantity of the product in the Order",
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "dto.CreateOrderReq": {
            "type": "object",
            "required": [
                "address",
                "amount",
                "order_items"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/dto.CreateAddressReq"
                },
                "amount": {
                    "description": "Total amount of the order",
                    "type": "number"
                },
                "order_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateOrderItemReq"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Gin 3at",
	Description:      "This is a server for Gin 3at API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
